# Basic dependabot.yml file with configuration for npm managers

version: 2
updates:
  # Enable version updates for npm
  - package-ecosystem: "npm"
    # Look for `package.json` and `lock` files in the `root` directory
    directory: "/"
    # Check the npm registry for updates every day (weekdays)
    schedule:
      interval: "weekly"
    commit-message:
      # Prefix all commit messages with "npm"
      prefix: "npm"
    reviewers:
      - "kyleju"
      - "jrobbins"
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"
    commit-message:
      # Prefix all commit messages with "docker"
      prefix: "docker"
    reviewers:
      - "jrobbins"
      - "jcscottiii"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      actions-org:
        patterns: ["actions/*"]
    commit-message:
      # Prefix all commit messages with "gh-actions"
      prefix: "gh-actions"
