application: cr-status
version: 2016-07-25
runtime: python27
threadsafe: true
api_version: 1

# default_expiration: "30s"

builtins:
- remote_api: on

libraries:
- name: webapp2
  version: "latest"
- name: django
  version: "1.4" #"latest"
# - name: setuptools
#   version: latest

env_variables:
  DJANGO_SETTINGS_MODULE: 'settings'

handlers:

# Static handlers ---------------------------------------------------------------
- url: /favicon\.ico
  static_files: static/img/chromium-128.png
  upload: static/img/chromium-128\.png

- url: /robots\.txt
  static_files: static/robots.txt
  upload: static/robots\.txt

- url: /service-worker\.js
  static_files: static/dist/service-worker.js
  upload: static/dist/service-worker\.js
  expiration: "0m"
  secure: always

- url: /static
  static_dir: static
  #expiration: 30s
  http_headers:
    Access-Control-Allow-Origin: "*"

# Metrics data handlers --------------------------------------------------------
- url: /data/.*
  script: metrics.app

# Admin ------------------------------------------------------------------------
- url: /admin/gae/.*
  script: google.appengine.ext.admin.application
  login: admin

- url: /cron/.*
  script: admin.app
  login: admin # Prevents raw access to this handler. Cron runs as admin.

- url: /admin/features/.*
  script: admin.app
  secure: always

- url: /admin/users/.*
  script: users.app
  login: admin
  secure: always

- url: /admin/.*
  script: google.appengine.ext.admin.application
  login: admin
  secure: always

# Main server ------------------------------------------------------------------
# features.xml needs to support HTTP as well as HTTPS, as some RSS backends don't support SNI certs.
# Same issue as what's described at https://github.com/Polymer/blog/issues/7
- url: /(features|samples).xml
  script: server.app
  secure: optional

- url: /.*
  script: server.app
  secure: always

skip_files:
- ^(.*/)?app\.yaml
- ^(.*/)?app\.yml
- ^(.*/)?index\.yaml
- ^(.*/)?index\.yml
- ^(.*/)?#.*#
- ^(.*/)?.*~
- ^(.*/)?.*\.py[co]
- ^(.*/)?.*/RCS/.*
- ^(.*/)?\..*
- ^(.*/)?.*\.csv$
- ^(.*/)?.*\.psd$
- ^(.*/)?.*\.sql[3]$
- ^(.*/)?.*\.sh$
- ^(.*/)?.*\.scss$
- ^http2push/example
- ^http2push/site
- ^(.*/)?node_modules
- ^(.*/)?tests
- ^(.*/)?.[LICENSE|PATENTS|AUTHORS|CONTRIBUTING|COPYING](\.md)?
- ^(.*/)?.*\.md$
