application: cr-status
version: 20140622
runtime: python27
threadsafe: true
api_version: 1

# default_expiration: "30s"

builtins:
- remote_api: on

libraries:
- name: webapp2
  version: "latest"
- name: django
  version: "1.4" #"latest" 
# - name: setuptools
#   version: latest

env_variables:
  DJANGO_SETTINGS_MODULE: 'settings'

handlers:

# Static handlers ---------------------------------------------------------------
- url: /favicon\.ico
  static_files: static/img/chromium-128.png
  upload: static/img/chromium-128\.png

- url: /static
  static_dir: static
  #expiration: 30s
  http_headers:
    Access-Control-Allow-Origin: "*"

# Metrics data handlers --------------------------------------------------------
- url: /data/.*
  script: metrics.app

# Admin ------------------------------------------------------------------------
- url: /admin/gae/.*
  script: google.appengine.ext.admin.application
  login: admin

- url: /cron/metrics
  script: admin.app
  login: admin # Prevents raw access to this handler. Cron runs as admin.

- url: /admin/features/.*
  script: admin.app
  login: required

- url: /admin/users/.*
  script: users.app
  login: admin

- url: /admin/.*
  script: google.appengine.ext.admin.application
  login: admin
  
# Main server ------------------------------------------------------------------
- url: /.*
  script: server.app

skip_files:
- ^(.*/)?app\.yaml
- ^(.*/)?app\.yml
- ^(.*/)?index\.yaml
- ^(.*/)?index\.yml
- ^(.*/)?#.*#
- ^(.*/)?.*~
- ^(.*/)?.*\.py[co]
- ^(.*/)?.*/RCS/.*
- ^(.*/)?\..*
- ^(.*/)?.*\.csv$
- ^(.*/)?.*\.psd$
- ^(.*/)?.*\.sql[3]$
- ^(.*/)?.*\.sh$
- ^(.*/)?.*\.scss$
- ^static/js/polymer-all
- ^(.*/)?node_modules
- ^(.*/)?.[LICENSE|PATENTS|AUTHORS|CONTRIBUTING|COPYING](\.md)?
