runtime: python27
threadsafe: true
api_version: 1
instance_class: F4

# default_expiration: "30s"

builtins:
- remote_api: on

handlers:

# Static handlers ---------------------------------------------------------------
- url: /favicon\.ico
  static_files: static/img/chromium-128.png
  upload: static/img/chromium-128\.png
  secure: always

- url: /robots\.txt
  static_files: static/robots.txt
  upload: static/robots\.txt
  secure: always

- url: /static
  static_dir: static
  #expiration: 30s
  application_readable: true # So static assets can be read by inline_file django tag.
  http_headers:
    Access-Control-Allow-Origin: "*"
  secure: always

# Metrics data handlers --------------------------------------------------------
- url: /data/.*
  script: api.metricsdata.app
  secure: always

# Admin ------------------------------------------------------------------------
- url: /cron/.*
  script: internals.fetchmetrics.app
  # Any cron job must be harmless if it is called too often or with bad args

- url: /tasks/.*
  script: internals.notifier.app
  # Header checks prevent raw access to this handler.  Tasks have headers.

- url: /_ah/bounce
  script: internals.notifier.app
  login: admin # Prevents raw access to this handler.

- url: /admin/blink.*
  script: pages.blink_handler.app
  login: required # non-admin
  secure: always

- url: /admin/subscribers
  script: pages.blink_handler.app
  login: required # non-admin
  secure: always

- url: /admin/features/.*
  script: pages.intentpreview.app
  login: required # non-admin
  secure: always

- url: /guide/.*
  script: pages.guide.app
  login: required # non-admin
  secure: always

- url: /admin/users/.*
  script: pages.users.app
  login: admin
  secure: always

- url: /settings
  script: pages.users.app
  secure: always

# Main server handlers ---------------------------------------------------------
- url: /
  script: pages.featurelist.app

- url: /features/schedule
  script: pages.schedule.app
  secure: always

- url: /features.*
  script: pages.featurelist.app

- url: /feature/.*
  script: pages.featuredetail.app

- url: /samples.*
  script: pages.samples.app

- url: /metrics.*
  script: pages.metrics.app

- url: /omaha_data
  script: pages.metrics.app

- url: /api/.*
  script: api.register.app
  secure: always


includes:
- skip_files.yaml
- env_vars.yaml

inbound_services:
- mail
- mail_bounce

libraries:
- name: grpcio
  version: 1.0.0
- name: ssl
  version: latest

env_variables:
  GAE_USE_SOCKETS_HTTPLIB : ''
