services:
  db:
    image: google/cloud-sdk:402.0.0-emulators
    restart: unless-stopped
    command: sh -c "gcloud beta emulators datastore start --project=cr-status-staging --host-port 0.0.0.0:$${DB_PORT} --no-store-on-disk --use-firestore-in-datastore-mode"
    environment:
      DB_PORT: 15606

  dsadmin:
    image: ghcr.io/remko/dsadmin:v0.18.1
    entrypoint: /ko-app/dsadmin -port 8888
    depends_on:
      - db
    network_mode: service:db
    environment:
      DATASTORE_PROJECT_ID: cr-status-staging
      DATASTORE_EMULATOR_HOST: "db:15606"
