version: '3.8'

services:
  app:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
      args:
        # Update 'VARIANT' to pick a version of Python: 3, 3.10, 3.9, 3.8, 3.7, 3.6
        # Append -bullseye or -buster to pin to an OS version.
        # Use -bullseye variants on local arm64/Apple Silicon.
        VARIANT: 3.9-bullseye
        # Optional Node.js version to install
        NODE_VERSION: "12"

    volumes:
      - ..:/workspace:cached  

    # Overrides default command so things don't shut down after the process ends.
    command: sleep infinity

    # Runs app on the same network as the database container, allows "forwardPorts" in devcontainer.json function.
    network_mode: service:db

    environment:
      DATASTORE_PROJECT_ID: cr-status-staging
      DATASTORE_EMULATOR_HOST: localhost:15606

  db:
    image: google/cloud-sdk:402.0.0-emulators
    restart: unless-stopped
    command: gcloud beta emulators datastore start --project=cr-status-staging --host-port 0.0.0.0:15606 --no-store-on-disk --consistency=1.0

  dsadmin:
    image: ghcr.io/remko/dsadmin:v0.18.1
    entrypoint: /ko-app/dsadmin -port 8888
    depends_on:
      - db
    network_mode: service:db
    environment:
      DATASTORE_PROJECT_ID: cr-status-staging
      DATASTORE_EMULATOR_HOST: "db:15606"
